import sys
import glob
import os


def safe_print(msg):
    """Print to stdout, falling back to bytes if the console cannot encode the text."""
    try:
        print(msg)
    except UnicodeEncodeError:
        sys.stdout.buffer.write((msg + "\n").encode("utf-8", "replace"))


def typ_str(s):
    """Escape a string for embedding in a Typst string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def find_cover(name):
    for ext in ("jpg", "jpeg", "png"):
        path = f"assets/{name}_cover.{ext}"
        if os.path.exists(path):
            return f"/assets/{name}_cover.{ext}"
    return None


def find_artist_images(name):
    arts = []
    for ext in ("jpg", "jpeg", "png"):
        arts.extend(glob.glob(f"assets/{name}_artist*.{ext}"))
    arts.sort()
    if not arts:
        for ext in ("jpg", "jpeg", "png"):
            path = f"assets/{name}_artist.{ext}"
            if os.path.exists(path):
                arts = [path]
                break
    return [f"/assets/{os.path.basename(a)}" for a in arts]


def main():
    name = sys.argv[1]
    basename = name

    cover_image = find_cover(basename)
    artist_images = find_artist_images(basename)

    lrc_exists = os.path.exists(f"medias/{basename}.lrc")
    lrc_path = f"/medias/{basename}.lrc" if lrc_exists else None
    if not lrc_exists:
        safe_print(f"Warning: medias/{basename}.lrc not found (rendering empty lyrics)")

    cover_arg = f'"{typ_str(cover_image)}"' if cover_image else "none"
    lrc_arg = f'"{typ_str(lrc_path)}"' if lrc_path else "none"
    if artist_images:
        items = ", ".join(f'"{typ_str(a)}"' for a in artist_images)
        trailing = "," if len(artist_images) == 1 else ""
        artists_arg = f"({items}{trailing})"
    else:
        artists_arg = "()"

    # Parameters grouped by relevance: identity, layout, then typography.
    # Active params are uncommented; optional params are commented out.
    param_lines = [
        f'  name: "{typ_str(basename)}",',
        f"  cover: {cover_arg},",
        f"  artists: {artists_arg},",
        f"  lrc: {lrc_arg},",
        "  left-ratio: 0.35,",
        "  spacing_all: 10pt,",
        "  lyrics-columns: 1,",
        "  // lyrics-column-widths: (1.2fr, 0.8fr),",
        "  // lyrics-columns-split: (20,),",
        "  // image-inset: (top: 0pt, left: 0pt),",
        "  // lyrics-inset: (top: 0pt, left: 0pt),",
    ]
    if len(artist_images) > 1:
        param_lines.extend(
            [
                "  // artist-grid-cols: 3,",
                "  // artist-grid-rows: 1,",
            ]
        )
    param_lines.extend(
        [
            "  lyrics-size: 0.55em,",
        ]
    )

    content = (
        "// Generated by scripts/gen_typ.py\n"
        '#import "/scripts/lyric.typ": lyric-poster\n\n'
        "#lyric-poster(\n" + "\n".join(param_lines) + "\n)\n"
    )

    out_dir = "_output/pdfs"
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{basename}.typ")

    if os.path.exists(out_path):
        safe_print(f"Skipped: {out_path} already exists (delete it to regenerate)")
        return

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    safe_print(f"Generated: {out_path}")


if __name__ == "__main__":
    main()
